export const translations = {
  en: {
    sign_in: {
      title: 'Login to your account',
      button: 'Sign In',
      user_name: {
        label: 'User Name',
        placeholder: 'Enter your user name',
        required: 'Username is required',
        invalid: 'Enter a valid username',
      },
      password: {
        label: 'Password',
        placeholder: 'Enter your password',
        required: 'Password is required',
        invalid: 'Password must be at least 8 characters',
      },
      success: 'You have signed in successfully',
      invalid_credentials: 'Invalid username or password',
    },
    home_screens: {
      index: 'Home',
      search: 'Search',
      ad_details: 'Ad Details',
    },
    menu_screens: {
      menu: 'Menu',
      change_lang: 'Change Language',
    },
    menu_items: {
      change_lang: 'Change Language',
      logout: {
        title: 'Log Out',
        message: 'Are you sure you want to log out?',
        cancel: 'Cancel',
        confirm: 'Log Out',
      },
    },
    home_screen: {
      all_categories: 'All Categories',
      search: 'Search',
    },
    ad_details: {
      mileage: 'Mileage:',
      seller: 'Seller:',
      area: 'Area:',
      area_unit: 'm²',
      beds: 'Beds:',
      baths: 'Baths:',
      agent: 'Agent:',
    },
    category_list: {
      cars: 'Cars',
      apartments: 'Apartments',
      mobiles: 'Mobiles',
    },
    search_screen: {
      searching: 'Searching...',
      no_result_found: 'No results found',
      search_placeholder: 'Search by title',
    },
    filter_bottom_sheet: {
      title: 'Filter Results',
      apply: 'Apply',
      reset: 'Reset',
      location: {
        label: 'Location',
        placeholder: 'Enter a location',
      },
      min_price: 'Min price',
      max_price: 'Max price',
      category: 'Category',
      all: 'All categories',
      cars: 'Cars',
      apartments: 'Apartments',
      mobiles: 'Mobiles',
    },
  },
  ar: {
    sign_in: {
      title: 'تسجيل الدخول إلى حسابك',
      button: 'تسجيل الدخول',
      user_name: {
        label: 'اسم المستخدم',
        placeholder: 'أدخل اسم المستخدم',
        required: 'اسم المستخدم مطلوب',
        invalid: 'أدخل اسم مستخدم صالح',
      },
      password: {
        label: 'كلمة المرور',
        placeholder: 'أدخل كلمة المرور',
        required: 'كلمة المرور مطلوبة',
        invalid: 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل',
      },
      success: 'تم تسجيل الدخول بنجاح',
      invalid_credentials: 'اسم المستخدم أو كلمة المرور غير صحيحة',
    },
    home_screens: {
      index: 'الرئيسية',
      search: 'بحث',
      ad_details: 'تفاصيل البيع',
    },
    menu_screens: {
      menu: 'القائمة',
      change_lang: 'تغيير اللغة',
    },
    menu_items: {
      change_lang: 'تغيير اللغة',
      logout: {
        title: 'تسجيل الخروج',
        message: 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
        cancel: 'إلغاء',
        confirm: 'تسجيل الخروج',
      },
    },
    home_screen: {
      all_categories: 'جميع الفئات',
      search: 'ابحث',
    },
    ad_details: {
      mileage: 'عدد الكيلومترات:',
      seller: 'البائع:',
      area: 'المساحة:',
      area_unit: 'متر مربع',
      beds: 'عدد الغرف:',
      baths: 'عدد الحمامات:',
      agent: 'الوكيل:',
    },
    category_list: {
      cars: 'سيارات',
      apartments: 'شقق',
      mobiles: 'هواتف محمولة',
    },
    search_screen: {
      searching: 'جاري البحث...',
      no_result_found: 'لم يتم العثور على نتائج',
      search_placeholder: 'ابحث عن عنوان',
    },
    filter_bottom_sheet: {
      title: 'تصفية النتائج',
      apply: 'تطبيق',
      reset: 'إعادة تعيين',
      location: {
        label: 'الموقع',
        placeholder: 'أدخل موقعًا',
      },
      min_price: 'السعر الأدنى',
      max_price: 'السعر الأقصى',
      category: 'الفئة',
      all: 'جميع الفئات',
      cars: 'سيارات',
      apartments: 'شقق',
      mobiles: 'هواتف محمولة',
    },
  },
};
